# Generated by Django 4.2.13 on 2024-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adress',
            field=models.TextField(null=True),
        ),
    ]
