# Generated by Django 4.2.13 on 2024-07-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_order_orderitem_order'),
        ('core', '0004_customuser_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='user_orders', to='cart.order'),
        ),
    ]
