# Generated by Django 5.0.6 on 2024-06-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_seria_item_setia_alter_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='setia',
        ),
        migrations.AddField(
            model_name='item',
            name='seria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item.seria'),
        ),
    ]
