# Generated by Django 4.2.13 on 2024-07-05 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 7, 5, 18, 33, 27, 246770, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
